<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MySolution.BusinessLayers\MySolution.BusinessLayers.csproj" />
    <ProjectReference Include="..\MySolution.DataLayers\MySolution.DataLayers.csproj" />
    <ProjectReference Include="..\MySolution.DomainModel\MySolution.DomainModel.csproj" />
  </ItemGroup>

</Project>
